export const MUTATION_REGISTER_USER = 'MUTATION_REGISTER_USER';
export const MUTATION_LOGIN_USER = 'MUTATION_LOGIN_USER';
export const MUTATION_LOGOUT_USER = 'MUTATION_LOGOUT_USER';

export const QUERY_GET_CURRENT_USER = 'QUERY_GET_CURRENT_USER';